baseurl = "https://d3buggr.dev"
title = "d3buggr"
copyright = "Copyright 2020"
canonifyurls = true
paginate = 5

googleAnalytics = ""

theme = "strange-case"
enableEmoji = true

[params]
	colorScheme = "scheme-darkbrown"
	DateFormat = "2 Jan 2006"
	description = "thoughts compiled!"
	sidebarFreeText = "Solving problems, optimizing things, trying out different stuff related to computers. Let's try out something unique that we both never knew!"
