baseurl = "https://d3buggr.dev"
title = "d3buggr"
description = "on the path of truth"
copyright = "Copyright 2022. All Rights Reserved"
canonifyurls = true
paginate = 10

googleAnalytics = "G-GDJLZ3DYVX"

theme = "blackburn"
enableEmoji = true

[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"

# [[menu.main]]
# 	name = "Github"
# 	pre = "<i class='fa-brands fa-github fa-fw'></i>"
# 	weight = 3
# 	identifier = "github"
# 	url = "https://github.com/d3buggrDev/"

# [param]


[social]
	twitter="d3buggr"
	github="d3buggrDev"