name: hugo publish

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest
        extended: true

    - name: Build
      run: cd blog-gen-hugo && hugo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: d3buggrDev/d3buggrDev.github.io
        PUBLISH_BRANCH: main
        PUBLISH_DIR: blog-gen-hugo/public
      with:
        emptyCommits: false
        commitMessage: ${{ github.event.head_commit.message }}
